# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

tone_instructions: >
  Expert TypeScript and React reviewer. Concise, actionable feedback
  focused on correctness, performance, and maintainability. Be direct.

early_access: true
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  collapse_walkthrough: true
  commit_status: true
  review_status: true
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_prs: true
  poem: false
  abort_on_close: true

  suggested_labels: true
  auto_apply_labels: true
  labeling_instructions:
    - label: "breaking-change"
      instructions: "Apply when changes break backward compatibility"
    - label: "feature"
      instructions: "Apply when adding new functionality"
    - label: "bug"
      instructions: "Apply when fixing bugs"
    - label: "refactor"
      instructions: "Apply for code refactoring without behavior changes"
    - label: "dependencies"
      instructions: "Apply when updating dependencies"
    - label: "performance"
      instructions: "Apply for performance improvements"

  path_filters:
    - "packages/**/*.{ts,tsx}"
    - "**/*.config.{ts,js}"
    - "**/tsconfig.json"
    - "**/biome.json"
    - "!**/dist/**"
    - "!**/node_modules/**"
    - "!bun.lock"

  path_instructions:
    - path: "packages/core/src/**/*.{ts,tsx}"
      instructions: |
        - Strict TypeScript: no `any`, proper generics
        - React hooks: correct dependency arrays, rules of hooks
        - Zero styling deps: vanilla CSS class names only, no CSS-in-JS
        - Public exports must have JSDoc documentation
        - Check for unnecessary re-renders in components

    - path: "packages/core/src/utils/**/*.ts"
      instructions: |
        - Pure functions preferred, no side effects
        - Validate edge cases (empty strings, zero values, NaN)
        - Math functions should document their formulas

    - path: "packages/core/src/renderers/**/*.ts"
      instructions: |
        - Verify renderer interface consistency across CSS/Canvas/WebGL
        - Check for browser API availability guards
        - Performance-critical: flag unnecessary allocations

    - path: "**/*.test.{ts,tsx}"
      instructions: |
        - Descriptive test names: "should X when Y"
        - Test edge cases and error conditions
        - No .only or .skip left in

    - path: "packages/**/index.ts"
      instructions: |
        - Review public API surface for breaking changes
        - Ensure consistent export naming conventions

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "[skip-review]"
    drafts: false
    base_branches:
      - "main"

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  pre_merge_checks:
    docstrings:
      mode: "warning"
      threshold: 80
    custom_checks:
      - name: "No console.log"
        pattern: "console\\.(log|debug|info)"
        message: "Remove console statements before merging"
        instructions: "Flag any console.log, console.debug, or console.info statements in production code"
        level: "warning"
      - name: "No focused tests"
        pattern: "(describe|it|test)\\.only"
        message: "Remove .only from tests before merging"
        instructions: "Flag any .only() calls on describe, it, or test blocks that would skip other tests"
        level: "error"

  enable_prompt_for_ai_agents: true

tools:
  biome:
    enabled: true
  eslint:
    enabled: false
  gitleaks:
    enabled: true
  ast-grep:
    enabled: true
  semgrep:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true

  # Disabled — not relevant
  ruff:
    enabled: false
  pylint:
    enabled: false
  rubocop:
    enabled: false
  golangci-lint:
    enabled: false
  clippy:
    enabled: false
  swiftlint:
    enabled: false

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - "**/AGENTS.md"
  learnings:
    scope: "local"
